// <auto-generated />
using System;
using Consolidado.Worker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Consolidado.Worker.Migrations
{
    [DbContext(typeof(ConsolidadoDbContext))]
    [Migration("20260327165023_InitialConsolidado")]
    partial class InitialConsolidado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Dominio.Entities.EventoProcessado", b =>
                {
                    b.Property<Guid>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataProcessamento")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventoId");

                    b.ToTable("EventosProcessados", (string)null);
                });

            modelBuilder.Entity("Core.Dominio.Entities.SaldoDiario", b =>
                {
                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DataReferencia");

                    b.ToTable("SaldosDiarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
